### ISSUE TITLE
Add  custom checks to wp-strap’s Wordpress Plugin Boilerplate

### ISSUE THREAD

**Issue by twobyte** [micropackage/requirements#11]
Thanks for doing this!

Do you have any tips on where the CustomCheck class file should be loaded when trying to create one within this Wordpress Plugin Boilerplate?

https://github.com/wp-strap/wordpress-plugin-boilerplate/blob/3f02a0e85eea155ad7fbece85a6abe52ec3a9629/src/Config/Requirements.php#L64

I had real trouble loading this class as per your example, and ended up doing a workaround that didn’t use the requirements micropackage at all!

**Comment by jakubmikita** [comment]
Hey @twobyte

check out [this plugin](https://github.com/BracketSpace/Notification-Signature/blob/develop/src/classes/Runtime.php#L67) where we define a custom check while doing the initialization.

I hope this helps you!

**Comment by twobyte** [comment]
That’s really helpful, thanks @Kubitomakita
