### ISSUE TITLE
What's the meaning of the 'custom-check' value?

### ISSUE THREAD

**Issue by ghost** [micropackage/requirements#3]
First of all: excellent package.

When building custom rules, given the example, what the 'something-else' string is gonna be for?
It seems an arbitrary value never used. Do you confirm?

`'custom-check' => 'something else',`

**Comment by jakubmikita** [comment]
Thanks!

This value (various type) is used for the check. If you are adding a simple check, you could just use bool here, ie:

```
'is-something-active' => true,
```

When passing `false`, this condition would need to be satisfied.

In other rules, you can pass here an array or string.

Let me know if you'll need more guidance!

**Comment by ghost** [comment]
Hi @Kubitomakita and thanks for the quick reply.
So basically, passing `false` is mandatory in order to determine the result of the custom checks via the `check()` method of my custom 'CustomCheck' class? - At least, that seems reasonable.

**Comment by jakubmikita** [comment]
Yep, that's correct

**Comment by ghost** [comment]
Cool, TY.
