### ISSUE TITLE
Text domain is a literal string

### ISSUE THREAD

**Issue by szepeviktor** [micropackage/requirements#4]
POEdit and WP-CLI `wp i18n make-pot src --domain='Requirements::$textdomain'` is not able to generate a `.pot` file from gettext calls with variables.

```php
__( 'Required plugin: %s', Requirements::$textdomain )
```

Please consider using string literals.
I know, I know.

**Comment by jakubmikita** [comment]
Well, the package should be really translated here, not in the project it's being used, so it's not creating any problems. We've been using the variable just for convenience as it's super long.

Ref: https://github.com/micropackage/requirements/blob/develop/package.json#L5
